### ISSUE TITLE
'strong passwords' do not accept Apple generated passwords due to requirement for symbols

### ISSUE THREAD

**Issue by rocos-david** [team-rocos/platform#1]
Apple generated ‘strong passwords’ are rejected when creating an account.

For long enough secure passwords they should not need symbols

**Comment by rocos-yishi** [comment]
Can you please show us the example of the generated password?

**Comment by rocos-david** [comment]
Roadmap item to allow passwords over 12 characters to not need symbols

**Comment by rocos-david** [comment]
@edwinhayes, this update is now applied to production. Passwords longer than 12 characters no longer need special characters.
