### ISSUE TITLE
Portal not loading on Safari 12

### ISSUE THREAD

**Issue by rstinear** [team-rocos/platform#10]
**Describe the bug**
Raised through #9. Safari 12 display a syntax error in its console: [Error] SyntaxError: Invalid regular expression: invalid group specifier name
(anonymous function) (main.89877e72b4300c7b0558.js:1)

**To Reproduce**
1. Go to portal.rocos.io in Safari 12
2. Observe blank page

**Expected behavior**
Portal should load

**Screenshots**
![image](https://user-images.githubusercontent.com/37167554/52449932-e1394f00-2b9d-11e9-98d8-0a01f69dd52d.png)

**Comment by e10101** [comment]
It is a regular expression bug on Safari browser. Bug fixed! This fix will be released in the next version.

**Comment by rocos-yishi** [comment]
It is a Regex bug on Safari browser. 

The bug has been fixed and it will be released in the next version.

**Comment by edwinhayes** [comment]
Can you confirm what "released in the next version" means in terms of updates to the agent/backend/portal during this closed beta?

**Comment by rstinear** [comment]
@edwinhayes we decided to do it as a hotfix instead, so the portal has been updated just to resolve the regex issue.

In terms of future releases - we'll provide some information closer to the next release in terms of new features, any impact to users etc.

**Comment by r3mafe** [comment]
> It is a Regex bug on Safari browser.

Could you please provide a proof link? Facing similar behaviour on another software piece and can't find any relative information.

**Comment by rocos-yishi** [comment]
@r3mafe 
Have a look: https://stackoverflow.com/a/51568859/4288118
