### ISSUE TITLE
Unable to delete projects

### ISSUE THREAD

**Issue by edwinhayes** [team-rocos/platform#13]
Right now, it seems like there is no way to delete a project once you've created it?  I'm slowing getting an increasing number of MAVLink Tutorials!

**Comment by neno-k** [comment]
Hi @edwinhayes , we are currently working on this feature and it will be part of the next major release.

**Comment by rocos-david** [comment]
@edwinhayes you can now delete a project that you created.  Go to the Projects page, use the 'more' icon on the top right of the project and choose delete. You will be asked to enter the project name as confirmation.  All data related to the project including any running virtual robots and historic data will be deleted permanently.
