### ISSUE TITLE
Can't create new Mavlink Template Project

### ISSUE THREAD

**Issue by edwinhayes** [team-rocos/platform#15]
I can no longer create new Mavlink Template Projects, I get an error "status 400" instead.  I can still create new blank projects.

**Comment by neno-k** [comment]
Hi @edwinhayes , can you please force a refresh on the browser to make sure you get the latest version and logout/login of the portal - thanks Neno

**Comment by edwinhayes** [comment]
Hmm ok, had to refresh without caching, but now seems to be working.

**Comment by rocos-david** [comment]
@edwinhayes we are looking at ways to solve client side refresh when we do updates that have breaking changes between client (cached) and server communication.
