### ISSUE TITLE
MAVLink Tutorial Virtual Robots Not Connected

### ISSUE THREAD

**Issue by edwinhayes** [team-rocos/platform#2]
**Describe the bug**
Virtual robots in the MAVLink tutorial project do not seem connect.

**To Reproduce**
1. Create a new MAVLink tutorial project.
2. Click on the list of robots.
3. Two virtual robots appears.
4. Status indicator for both robots remains greyed out.

**Expected behavior**
I think the expected behaviour is that the indicator turns a different colour, to indicate a data connection with the agent on the simulated robot?  And some data streams are automatically created.  At least this is the idea I get from reading the tutorial.

**Screenshots**
![screen shot 2019-02-05 at 13 21 25](https://user-images.githubusercontent.com/15720644/52246029-f9fcf700-2948-11e9-8321-7b3a3c1ba08e.png)

**Computer:**
 - OS: MacOS 10.14
 - Browser: Safari
 - Version: 12

**Comment by neno-k** [comment]
Hi Edwin, thanks for reporting this, we can see from the logs that the second virtual robot from the MAVLink tutorial did not get deployed. We are investigating what went wrong, and also working on improving the status on the Robot list page. Thanks Neno

**Comment by edwinhayes** [comment]
FYI, I decided to make another project, in case my messing around had become a problem.  In the new project, the exact same thing happens: the first virtual robot gets deployed by doesn't seem to actually be online, and the second virtual robot gets stuck in the 'deploying' state.

**Comment by neno-k** [comment]
Hi @edwinhayes , we have deployed a hotfix to resolve this do let me know if you are still experiencing issues - thanks

**Comment by edwinhayes** [comment]
@neno-k Do you expect this hot fix to resolve the issue for existing projects, or just prevent it from occurring on future new projects?

**Comment by edwinhayes** [comment]
Well, either way it doesn't seem to have fixed anything.  Now, if anything, more virtual robots are stuck in the 'deploying' state than before!

**Comment by edwinhayes** [comment]
Hey guys, any progress on this, or idea when it might be fixed?

**Comment by neno-k** [comment]
Hi @edwinhayes , apologies for the late reply, we have released another hotfix earlier in the week that resolves the issue above. This will not fix any robots deployed historically, for those you can delete them and add them again by going to 'Add Robot' -> 'Deploy Virtual'

**Comment by edwinhayes** [comment]
Now the robots seem to deploy reliably, but there is still no sign of any of them actually streaming any data.

**Comment by neno-k** [comment]
Hi @edwinhayes , this was an issue impacting safari and firefox browsers, we have deployed a fix for it now and you should see your robots come online and data showing up on the graphs

**Comment by edwinhayes** [comment]
Looks like success!  Thanks.
