### ISSUE TITLE
Agent stops working after some time.

### ISSUE THREAD

**Issue by edwinhayes** [team-rocos/platform#26]
After running for [not sure exactly, many days], the Agent has lost it's connection to the cloud, citing an authentication issue:

`level=error msg="live stream: received graph error rpc error: code = Unauthenticated desc = invalid auth token: Token is expired:"`

Restarting the agent restores normal operation.

**Comment by edwinhayes** [comment]
To clarify, this is an agent on a real robot.

**Comment by rocos-david** [comment]
Thanks, known issue with this version of the agent, doesn't auto update token on expiration.  The next major release will solve this along with several other enhancements.

**Comment by rstinear** [comment]
Fixed in release [v0.0.5-3163](https://docs.rocos.io/beta/docs/agent-release-notes)
