### ISSUE TITLE
When do changes to stream definitions get applied?

### ISSUE THREAD

**Issue by edwinhayes** [team-rocos/platform#27]
So, I turned off a stream, yet a couple of minutes later your graphs still seem to show data being transferred.  Is this expected behaviour?

![screen shot 2019-03-08 at 13 58 28](https://user-images.githubusercontent.com/15720644/53999992-974a8580-41aa-11e9-9700-5cd916699319.png)

**Comment by rocos-david** [comment]
Will review.  Those graphs do not currently update automatically, you need to click the refresh button. On the roadmap is the graph auto updating every 5 seconds if you are not zoomed in. Can you confirm if this is still not working if you click on refresh?

**Comment by edwinhayes** [comment]
Yep, I've smashed refresh a bunch of times.

**Comment by edwinhayes** [comment]
Further information, I came across this issue because I added a new piece of data to an existing stream definition, but founded it didn't immediately start coming through.  So if I had to guess, I guess the issue affects modifying stream definitions, not just enabling/disabling them?

**Comment by rocos-david** [comment]
Can replicate, backend team will resolve.

**Comment by rocos-david** [comment]
Bug fix related to streaming updates released.
