### ISSUE TITLE
Graphs escaping!

### ISSUE THREAD

**Issue by edwinhayes** [team-rocos/platform#28]
This is probably another Safari one?

It's fine at the default zoom level, but if you drag-select part of a graph to zoom in, this happens:

![screen shot 2019-03-08 at 14 02 51](https://user-images.githubusercontent.com/15720644/54000132-1770eb00-41ab-11e9-885d-97ab10232b1a.png)

Along with some cool flashing behaviour where sometimes the graph is drawing right across the page!

**Comment by rocos-david** [comment]
Chart controls updated, this should now be resolved in v0.1.0-3042
