### ISSUE TITLE
Need improved workflow for connecting robots.

### ISSUE THREAD

**Issue by edwinhayes** [team-rocos/platform#3]
The workflow for connecting a robot to ROCOS seems only suitable for connecting individual robots in a test environment.

1. `rocos-agent --init` is interactive; it could easily take comment line arguments instead.

2. The authorisation process is basically impossible to automate, impossible run on a computer which isn't being accessed by SSH but doesn't have a GUI, and just seems backwards.  We would rather enter some static information ahead of time on the robot side, then have an administrator approve one or more incoming connection from robots via the web interface.

**Comment by rstinear** [comment]
Thanks for the feedback @edwinhayes - we had some concepts for this and for #4 on our roadmap so good to see them reinforced - I've created #6 and #7 to roll up your suggestions and track them as enhancements.

**Comment by rocos-david** [comment]
Will be tracked from #6 and #7
