### ISSUE TITLE
Control of Y axis on graphs.

### ISSUE THREAD

**Issue by edwinhayes** [team-rocos/platform#31]
It would be nice to be able to control the scale of the Y axis in graphs a bit more to be able to force them to display a particular range (usually zero), so that rather than getting a really zigzag line which shows tiny fluctuations in value, you can get a nice flat line which shows that everything is normal.

For instance, you don't really care about your free memory being 2.0000GB or 2.0001GB, you just want to be able to glance at the screen and see a flat line that's well above zero!

**Comment by rocos-david** [comment]
For sure, on the roadmap.

**Comment by rocos-david** [comment]
This is deployed now in v0.1.0-3042.  https://app.developerhub.io/docs/beta/docs/portal-releases-notes
