### ISSUE TITLE
Quotes in project descriptions renders strangely.

### ISSUE THREAD

**Issue by edwinhayes** [team-rocos/platform#34]
Make a new project with the description "It's a test!".  On the account home page where projects are listed, this appears as "It&#x27;s a test!".  Oh no!

**Comment by rstinear** [comment]
Thanks Edwin, we'll look into it.

@rocos-yishi this is in build 0.1.0-4087

**Comment by neno-k** [comment]
Hi Edwin, this is resolved now - thanks Neno
