### ISSUE TITLE
Agent fails to start w. "could not create or load telemetry database: EOF"

### ISSUE THREAD

**Issue by edwinhayes** [team-rocos/platform#35]
Not sure when this started; might be related to an update you did?

**Comment by rstinear** [comment]
Hi Edwin, we did have this issue a few builds back, is this in the latest stable build (v0.0.6-3821)? We may had a regression if so.

**Comment by edwinhayes** [comment]
Lol, can't run "--version" with this error.  Uh... from JSON looks like v0.0.5-3163.  Will update.

**Comment by rstinear** [comment]
Did you get past this issue with a new build @edwinhayes ?

**Comment by edwinhayes** [comment]
Ah yes, I did.  It was carnage, because updating the agent pulled in updates for ROS, and then _everything_ was broken!
