### ISSUE TITLE
Running JS Demo

### ISSUE THREAD

**Issue by edwinhayes** [team-rocos/platform#40]
The JS demo for the turtlebot is cool, but oh man the 'Run' button needs to be stateful!  Otherwise if you're impatient, you queue up 1000000000 instances without realising!

**Comment by neno-k** [comment]
Hi @edwinhayes , thanks for this - this feature is still in development and got enabled accidentally in a recent update. I have created an item on our backlog based on your feedback to review the behavior of the Run button.
