### ISSUE TITLE
Storage Explorer Filtering Broken

### ISSUE THREAD

**Issue by edwinhayes** [team-rocos/platform#41]
**Describe the bug**
On the Storage Explorer page, filtering by Source does not work.

**To Reproduce**
1. Goto Storage Explorer.
2. Select a robot and sensible timescale.
3. Note some non-zero number of messages displayed under Preview.
4. Note that these messages include "/system/memory" messages.
5. Under the list of sources, check the corresponding memory message checkbox.
6. No messages are previewed (although the number of results seems correct).

**Expected behavior**
The messages should be shown in the preview field.

**Screenshots**

![Screen Shot 2019-10-02 at 13 06 03](https://user-images.githubusercontent.com/15720644/66009081-71ede200-e515-11e9-833f-7157176645de.png)
![Screen Shot 2019-10-02 at 13 06 14](https://user-images.githubusercontent.com/15720644/66009083-731f0f00-e515-11e9-8a45-199a8077a89a.png)

**Computer:**
 - OS: MacOS
 - Browser: Safari
 - Version: V12.0

**Comment by neno-k** [comment]
Hi @edwinhayes , this is resolved now and deployed - thanks Neno
